WITH CTECUSTO(NROEMPRESA, SEQPRODUTO, CUSTOBRUTOUNIT, DTAENTRADASAIDA) as
(SELECT 

nroempresa,
SEQPRODUTO,
CAST(avg(VLRCTOBRUTOUNIT) as decimal(10,4)),
max(DTAENTRADASAIDA)

FROM CONSINCO.MAXV_ABCMOVTOBASE_PROD
group by seqproduto, nroempresa),

TABELA_CUSTOBRT (SEQPRODUTO, SEQFILIAL, CUSTOBRUTOUNIT) AS
(select DISTINCT cte.seqproduto, cte.nroempresa, CAST(avg(a.VLRCTOBRUTOUNIT) AS DECIMAL(10,4)) AS CUSTOBRUTOUNIT from CTECUSTO cte
LEFT OUTER JOIN CONSINCO.MAXV_ABCMOVTOBASE_PROD a on a.seqproduto = cte.seqproduto

WHERE A.SEQPRODUTO = cte.SEQPRODUTO
AND A.NROEMPRESA = cte.NROEMPRESA
AND A.DTAENTRADASAIDA = cte.DTAENTRADASAIDA
AND A.NROEMPRESA IN (1, 2, 4, 5, 8, 9, 73, 77)
group by cte.seqproduto, cte.nroempresa
order by nroempresa asc)

SELECT
A.SEQPRODUTO,
A.NROEMPRESA,
A.MEDVDIAGERAL,
A.CLASSEABASTVLR,
A.ESTQLOJA,
A.ESTQDEPOSITO,
A.ESTQALMOXARIFADO,
A.ESTQTROCA,
A.ESTQOUTRO,
TO_CHAR(REPLACE(cbrt.CUSTOBRUTOUNIT, ',' , '.')) AS cto_bruto,
TO_CHAR(A.DTAULTVENDA, 'yyyy/mm/dd') as dtaultvenda


FROM CONSINCO.MRL_PRODUTOEMPRESA A
     LEFT JOIN TABELA_CUSTOBRT cbrt on A.SEQPRODUTO = cbrt.SEQPRODUTO
     
WHERE 
     A.SEQPRODUTO = cbrt.seqproduto
     AND A.NROEMPRESA = cbrt.SEQFILIAL
     
 order by a.seqproduto asc